
CREATE DATABASE hospital_db;

USE hospital_db;

SHOW TABLES;

SELECT * FROM departments;

SELECT COUNT(*) AS total_patients
FROM patients;

SELECT COUNT(*) AS total_doctors
FROM doctors;


SELECT COUNT(*) AS total_departments
FROM departments;

SELECT COUNT(*) AS total_appointments
FROM appointments;


SELECT COUNT(*) AS total_billing_records
FROM billing;


SELECT COUNT(*) AS total_prescriptions
FROM prescriptions;


SELECT COUNT(*) AS total_lab_tests
FROM lab_tests;

-- Display the structure of the patients table
DESCRIBE patients;

-- Find how many doctors work in each department
SELECT
    department_id,
    COUNT(*) AS doctor_count
FROM doctors
GROUP BY department_id
ORDER BY doctor_count DESC;


-- Count patients in each city
SELECT
    city,
    COUNT(*) AS patients_city
FROM patients
GROUP BY city
ORDER BY patients_city DESC;


-- Count male and female patients
SELECT
    gender,
    COUNT(*) AS total_patients
FROM patients
GROUP BY gender
ORDER BY gender DESC;

-- Calculate the average age of all patients
SELECT
    ROUND(AVG(age),2) AS patients_avg_age
FROM patients;

-- Display the oldest patient
SELECT
    name,
    age
FROM patients
ORDER BY age DESC
LIMIT 1;

-- Display the youngest patient
SELECT
    name,
    age
FROM patients
ORDER BY age
LIMIT 1;


-- Count appointments handled by each doctor
SELECT
    doctor_id,
    COUNT(*) AS total_appointments
FROM appointments
GROUP BY doctor_id
ORDER BY total_appointments DESC;

SELECT
    p.name,
    d.doctor_name
FROM patients AS p
JOIN appointments AS a
ON p.patient_id = a.patient_id
JOIN doctors AS d
ON a.doctor_id = d.doctor_id;


SELECT *
FROM patients p
LEFT JOIN doctors d
ON p.doctor_id = d.doctor_id;



SELECT

    p.patient_id,
    p.name,
    p.gender,
    p.age,
    p.city,
    p.admission_date,
    p.discharge_date,
    p.status,
    p.diagnosis,

    d.doctor_name,
    d.gender AS doctor_gender,
    d.experience_years,

    dept.department_name,

    a.appointment_date,
    a.appointment_status,

    b.bill_amount,
    b.payment_method,

    pr.medicine_name,
    pr.days,

    l.test_name,
    l.result

FROM patients p

LEFT JOIN doctors d
ON p.doctor_id = d.doctor_id

LEFT JOIN departments dept
ON p.department_id = dept.department_id

LEFT JOIN appointments a
ON p.patient_id = a.patient_id

LEFT JOIN billing b
ON p.patient_id = b.patient_id

LEFT JOIN prescriptions pr
ON p.patient_id = pr.patient_id

LEFT JOIN lab_tests l
ON p.patient_id = l.patient_id;


CREATE VIEW hospital_master_view AS

SELECT

    p.patient_id,
    p.name,
    p.gender,
    p.age,
    p.city,
    p.admission_date,
    p.discharge_date,
    p.status,
    p.diagnosis,

    d.doctor_name,
    d.gender AS doctor_gender,
    d.experience_years,

    dept.department_name,

    a.appointment_date,
    a.appointment_status,

    b.bill_amount,
    b.payment_method,

    pr.medicine_name,
    pr.days,

    l.test_name,
    l.result

FROM patients p

LEFT JOIN doctors d
ON p.doctor_id = d.doctor_id

LEFT JOIN departments dept
ON p.department_id = dept.department_id

LEFT JOIN appointments a
ON p.patient_id = a.patient_id

LEFT JOIN billing b
ON p.patient_id = b.patient_id

LEFT JOIN prescriptions pr
ON p.patient_id = pr.patient_id

LEFT JOIN lab_tests l
ON p.patient_id = l.patient_id;

SELECT *
FROM patients
WHERE age > 60;


-- Display all female patients.

SELECT *
FROM patients
WHERE gender = 'Female';


-- Display patients living in Hyderabad.

SELECT *
FROM patients
WHERE city = 'Hyderabad';


-- Display bills greater than ₹50,000.

SELECT *
FROM billing
WHERE bill_amount > 50000;


-- Display completed appointments.

SELECT *
FROM appointments
WHERE appointment_status = 'Completed';


SELECT
SUM(bill_amount) AS total_revenue
FROM billing;


-- Calculate average bill amount.

SELECT
AVG(bill_amount) AS average_bill
FROM billing;


-- Display the highest bill amount.

SELECT
MAX(bill_amount) AS highest_bill
FROM billing;


-- Display the lowest bill amount.

SELECT
MIN(bill_amount) AS lowest_bill
FROM billing;


-- ============================================================
-- STEP 18 : Revenue Generated by Each Department
-- ============================================================

-- Calculate total revenue generated by each department.

SELECT

    dept.department_name,
    SUM(b.bill_amount) AS total_revenue

FROM billing b

JOIN patients p
ON b.patient_id = p.patient_id

JOIN departments dept
ON p.department_id = dept.department_id

GROUP BY dept.department_name

ORDER BY total_revenue DESC;



SELECT

    dept.department_name,
    ROUND(AVG(b.bill_amount),2) AS average_bill

FROM billing b

JOIN patients p
ON b.patient_id = p.patient_id

JOIN departments dept
ON p.department_id = dept.department_id

GROUP BY dept.department_name

ORDER BY average_bill DESC;


SELECT

    p.name,
    b.bill_amount

FROM patients p

JOIN billing b
ON p.patient_id = b.patient_id

ORDER BY b.bill_amount DESC

LIMIT 10;

SELECT

    diagnosis,
    COUNT(*) AS total_patients

FROM patients

GROUP BY diagnosis

ORDER BY total_patients DESC;


SELECT

    payment_method,
    SUM(bill_amount) AS revenue

FROM billing

GROUP BY payment_method

ORDER BY revenue DESC;


SELECT

    department_id,
    COUNT(*) AS total_patients

FROM patients

GROUP BY department_id

HAVING COUNT(*) > 20;


SELECT

CASE

    WHEN age < 18 THEN 'Child'

    WHEN age BETWEEN 18 AND 40 THEN 'Adult'

    WHEN age BETWEEN 41 AND 60 THEN 'Middle Age'

    ELSE 'Senior'

END AS age_group,

COUNT(*) AS total_patients

FROM patients

GROUP BY age_group;


SELECT

    name,
    age

FROM patients

WHERE age >

(
    SELECT AVG(age)
    FROM patients
);


SELECT

    doctor_id,
    COUNT(*) AS total_appointments

FROM appointments

GROUP BY doctor_id

ORDER BY total_appointments DESC

LIMIT 5;

SELECT

    doctor_id,

    COUNT(*) AS total_appointments,

    RANK() OVER(
        ORDER BY COUNT(*) DESC
    ) AS doctor_rank

FROM appointments

GROUP BY doctor_id;


SELECT

    patient_id,

    name,

    bill_amount,

    ROW_NUMBER() OVER(
        ORDER BY bill_amount DESC
    ) AS row_num

FROM hospital_master_view;


SELECT

    patient_id,

    name,

    bill_amount,

    DENSE_RANK() OVER(
        ORDER BY bill_amount DESC
    ) AS bill_rank

FROM hospital_master_view;


SELECT

    MONTH(appointment_date) AS month,

    COUNT(*) AS total_appointments

FROM appointments

GROUP BY MONTH(appointment_date)

ORDER BY month;


SELECT

    YEAR(appointment_date) AS year,

    COUNT(*) AS total_appointments

FROM appointments

GROUP BY YEAR(appointment_date)

ORDER BY year;


SELECT

    patient_id,

    name,

    DATEDIFF(discharge_date, admission_date)
    AS days_in_hospital

FROM patients;


SELECT

    p.city,

    SUM(b.bill_amount) AS total_revenue

FROM billing b

JOIN patients p

ON b.patient_id = p.patient_id

GROUP BY p.city

ORDER BY total_revenue DESC;


SELECT

    doctor_name,

    experience_years

FROM doctors

ORDER BY experience_years DESC;


SELECT

    appointment_status,

    COUNT(*) AS total

FROM appointments

GROUP BY appointment_status;


SELECT VERSION();


USE hospital_db;
SELECT * FROM hospital_master_view;